modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"

[[mods]]
modId="overchargehearts"
version="1.21.1-1.0"
displayName="Overcharged Hearts"
authors="CrypCee"
description='''
Adds permanent Overcharged Hearts that extend the player's maximum life by consuming crafted heart items.
These bonus hearts regenerate outside combat and are lost upon death.
'''

[[dependencies.overchargehearts]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.overchargehearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
